---
- hosts: all

  vars:
    zookeeper_nodes: {} 
    
  tasks:
    - name: "Debug zookeeper servers list"
      when: zookeeper is defined 
      
      #set_fact: 
        #zookeeper_nodes[ '{{ zookeeper_vars.cluster_id }}' ]: "{{ zookeeper_nodes[ '{{ zookeeper_vars.cluster_id }}' ] }} + [ '{{ items ] }}' ]"
        #zookeeper_nodes: "{{ zookeeper_nodes + [ hostvars[item]['zookeeper'] ] }}"
        #zookeeper_nodes[index]: "{{ hostvars[item]['zookeeper'] }}"
        #zookeeper_nodes: "{{ zookeeper_nodes | combine ( { hostvars[item]['zookeeper'] } )  }}"
        #zookeeper_nodes: "{{ zookeeper_nodes +  [ hostvars[item]['zookeeper'] ] }}"

        #zookeeper_nodes: "{{ zookeeper_nodes }}"
      set_fact:
        zookeeper_nodes: "{{ zookeeper_nodes | combine(item) }}"

      debug:
        var: item
        #var: hostvars[item].zookeeper.node_id
        #var: zookeeper_nodes
        #var:  hostvars[item]['zookeeper']
       
      with_subelements:
        - "{{ zookeeper.clusters }}"
        - nodes

    
