---
- hosts: all

  vars:
    zookeeper_nodes: {} 
    current_clustername: ""
        
  tasks:
    - name: "Get clustername of current host"
      when:
        - zookeeper is defined 
        - item.1 == ansible_hostname
      set_fact:
        current_clustername: "{{ item.0['name'] }}"
      
      with_subelements:
        - "{{ zookeeper.clusters }}"
        - nodes
  
    - name: "Generate zookeeper cluster servers list"
      when: zookeeper is defined
      
      set_fact:
        zookeeper_nodes: "{{ zookeeper_nodes | combine(item.1) }}"
    
      with_subelements:
        - "{{ zookeeper.clusters }}"
        - nodes

    - name: "Debug zookeeper servers list"
      when: zookeeper is defined 

      debug:
        var: zookeeper_nodes
      
       

    
